version: '3'
services:
  zookeeper:
    image: 'wurstmeister/zookeeper:latest'
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: 'wurstmeister/kafka:latest'
    container_name: kafkaserver
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.29.168
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_NO_PARTITIONER_WARNING: 1
  
